language: java

install: true
before_install:
  - emacs24 --batch -l bin/install-org.el

script: bin/compile
env:
  global:
    - REPO_DIR=".repo"
    - TARGET_REPO="ungs-prog2/_"
    - TARGET_BRANCH="gh-pages"

branches:
  only:
    - next
    - master
    - test_travis

addons:
  apt:
    packages:
      - git  # For --date=format:
      - emacs24
    sources:
      - git-core
      - cassou-emacs

cache:
  directories:
    - $HOME/.emacs.d

deploy:
  - provider: script
    script: bin/publish
    on:
      branch:
        - next

notifications:
  email:
    on_success: never
