language: java

install: true
before_install:
  - emacs --batch -l bin/install-org.el

script: bin/compile
env:
  global:
    - REPO_DIR=".repo"
    - PREVIEW_REPO="ungs-prog2/_"
    - ARCHIVE_BRANCH="2016c1"

branches:
  only:
    - master
    - test_travis

addons:
  apt:
    packages:
      - git  # For --date=format:
      - emacs24
    sources:
      - git-core
      - cassou-emacs

# TODO: re-enable cache with Emacs 24.5
# cache:
#   directories:
#     - $HOME/.emacs.d

deploy:
  - provider: script
    script: bin/publish
    on:
      branch:
        - master

notifications:
  email:
    on_success: never
